function PrivacyPolicy() {
  return (
    <>
      <center style={{padding:"20px"}}>
        <p style={{ fontSize: "50px",fontWeight:"bold" ,color:"#00B98E"}}>PRIVACY POLICY</p>
      </center>
      <div className="paratandc">
        <h1 className="tandch1">1. GENERAL</h1>
        <p>
          <p>In this Privacy Notice, the following definitions are used: </p>
          <p>
            “Data” shall mean personal information, including sensitive personal
            information and special category personal data (as defined under
            Data Protection Laws) about you, which we collect, receive or
            otherwise process in connection with your use of our website and/or
            the Platform.
          </p>
          <p>
            {" "}
            “Cookies” means a small file placed on your device by our website or
            Platform when you either visit or use certain features of our
            website or Platform. A cookie generally allows a website or mobile
            application to remember your actions or preference for a certain
            period of time.{" "}
          </p>
          <p>
            “Data Protection Laws” shall mean any applicable law for the time
            being in force relating to the processing of Data.
          </p>
          <p>
            “Partners” shall mean select third parties (including Aurum Group
            Entities) with whom we have contracts for the businesses described
            in this Privacy Policy.
          </p>
          <p>
            {" "}
            “Service Providers” includes entities which provide services to and
            to whom we may disclose your Data for a specific purpose pursuant to
            a written contract.
          </p>
          <p>
            {" "}
            “Aurum Group Entity” shall mean Aurum RealEstate Developers Limited,
            and its subsidiaries, affiliates, associate companies and joint
            venture companies.
          </p>
          <p>
            {" "}
            “User or you” shall mean the natural person who accesses our website
            or Platform.
          </p>
          <p>
            {" "}
            This Privacy Policy primarily explains how we use your personal data
            when we act as a controller of your Data. Where we act as a
            “processor” on behalf of Aurum Group Entity or other participating
            entity (i.e. the “controller”), please refer to the relevant privacy
            policy of the relevant participating entity for information about
            how they use your Data.
          </p>
          <p>
            {" "}
            a) This document is an electronic record in terms of Information
            Technology Act, 2000 and rules there under as applicable and the
            amended provisions pertaining to electronic records in various
            statutes as amended by the Information Technology Act, 2000. This
            electronic record is generated by a computer system and does not
            require any physical or digital signatures.
          </p>
          <p>
            {" "}
            b) This document is published in accordance with the provisions of
            Rule 3 (1) of the Information Technology (Intermediaries guidelines)
            Rules, 2011 that require publishing the rules and regulations,
            privacy policy and Terms of Use for access or usage of the website
            or Platform. https://www. aurumrealestate.in/{" "}
          </p>
          <p>
            c) The headings of each section in this Policy are only for the
            purpose of organizing the various provisions under this Policy in an
            orderly manner, and shall not be used by either Party to interpret
            the provisions contained herein in any manner. Further, it is
            specifically agreed to by the Parties that the headings shall have
            no legal or contractual value.
          </p>
          <p>
            {" "}
            d) The use of the Website/Platform by the User is solely governed by
            this Policy as well as the Terms of Use (“Terms”, available at www.
            aurumrealestate.in.com/terms), and any modifications or amendments
            made thereto by the Company from time to time, at its sole
            discretion. The User expressly agrees and acknowledges that the
            Terms and Policy are co-terminus, and that expiry / termination of
            either one will lead to the termination of the other.
          </p>
          <p>
            {" "}
            e) The User unequivocally agrees that this Policy and the
            aforementioned Terms constitute a legally binding agreement between
            the User and the Company, and that the User shall be subject to the
            rules, guidelines, policies, terms, and conditions applicable to any
            service that is provided by the Website, and that the same shall be
            deemed to be incorporated into the Terms, and shall be treated as
            part and parcel of the same. The User acknowledges and agrees that
            no signature or express act is required to make these Terms and the
            Policy binding on the User, and that the User's act of visiting any
            part of the Platform/Website constitutes the User's full and final
            acceptance of the Policy and the aforementioned Terms.{" "}
          </p>
          <p>
            f) The Parties expressly agree that the Company retains the sole and
            exclusive right to amend or modify the Policy and the aforementioned
            Terms without any prior permission or intimation to the User, and
            the User expressly agrees that any such amendments or modifications
            shall come into effect immediately. The User has a duty to
            periodically check the Policy and Terms, and stay updated on their
            provisions and requirements. If the User continues to use the
            Website following such a change, the User will be deemed to have
            consented to any and all amendments / modifications made to the
            Policy and Terms. In so far as the User complies with the Policy and
            Terms, he/she is granted a personal, non-exclusive,
            non-transferable, revocable, limited privilege to enter, access and
            use the Website/Platform.
          </p>
        </p>
        <h1 className="tandch1">2. WHAT WE COLLECT</h1>
        <p>
          <p>
            We collect Data for various purposes set out in this Privacy Policy.
            This Data includes, without limitation, the following categories:{" "}
          </p>
          <p>
            (a) Contact information: first and last name, email address, postal
            address, country, phone number and other similar contact data.{" "}
          </p>
          <p>
            (b) Financial information: payment instrument information,
            transactions, transaction history, preferences, method, mode and
            manner of payment, spending pattern or trends, and other similar
            data.{" "}
          </p>
          <p>
            (c) Technical information: website, device and mobile app usage,
            Internet Protocol (IP) address and similar information collected via
            automated means, such as cookies, pixels and similar technologies.{" "}
          </p>
          <p>
            (d) Product and service information: Your website or Platform
            account number, registration information, and program-specific
            information, when you request products and/or services directly from
            us or participate in marketing programs.{" "}
          </p>
          <p>
            (e) Your reviews, feedback and opinions about our products,
            programmes and services.{" "}
          </p>
          <p>
            (f) Loyalty programme information: your loyalty information, account
            details, profile or password details and any frequent flyer or
            travel partner programme affiliation.
          </p>
          <p>
            {" "}
            (g) Transaction information: date of the transaction, transaction
            amount, transaction history and related details;{" "}
          </p>
          <p>
            (h) Other information (which may include sensitive personal
            information or special category personal data): Age, sex, date of
            birth, marital status, nationality, details of government
            identification documents provided, occupation or any other personal
            information provided by you.{" "}
          </p>
          <p>
            The User expressly agrees and acknowledges that the Company collects
            and stores the User’s personal information, which is provided by the
            User from time to time on the Website, including but not limited to
            the User's user name, passwords, email address, name, address, age,
            date of birth, sex, nationality, shopping preferences, browsing
            history, etc., as well as any images or other information
            uploaded/published by the User on the Website. The User is aware
            that this information will be used by the Company/Platform to
            provide services and features targeted at the User, that are most
            likely to meet the User’s needs, and also to customize and improve
            the Website to make its user's experiences safer and easier.
          </p>
          <p>
            {" "}
            If the User chooses to post messages / reviews / feedback anywhere
            on the Website, including but not limited to message boards, chat
            rooms, other message areas, etc., the User is aware that any and all
            such information provided / uploaded will be collected and stored by
            the Company indefinitely, and that such retained information may be
            used to resolve disputes, provide customer support, troubleshoot
            problems, etc., and that such information, if requested, may be
            provided to judicial or governmental authorities of requisite
            jurisdiction, or otherwise used by the Company/Website/Platform as
            permitted by applicable laws.
          </p>
          <p>
            {" "}
            Nothing contained herein shall be deemed to compel the
            Website/Company/Platform to store, upload, publish, or display in
            any manner content/reviews/surveys/feedback submitted by the User,
            and the User hereby expressly authorises the
            Website/Company/Platform to remove from the Website any such
            content, review, survey, or feedback submitted by the User, without
            cause or being required to notify the User of the same.
          </p>
        </p>
        <h1 className="tandch1">3. HOW WE COLLECT DATA</h1>
        <p>
          <p>We collect Data in the following ways: </p>
          <p>
            a. Information You Give Us: We receive and store any information you
            enter on our website or Platform or give us in any other way. Please
            see the section below, titled “Data Shared by You” for more
            information.{" "}
          </p>
          <p>
            b. Automatic Information We Collect: We use “cookies”, pixels and
            similar technologies to receive and store certain types of
            information whenever you interact with us. Please see the section
            below, titled “Data That is Collected Automatically” for more
            information.
          </p>
          <p>
            {" "}
            c. E-mail Communications: We often receive a confirmation (if your
            device supports such capabilities) when you open e-mail from us or
            click on a link in the e-mail. You can choose not to receive
            marketing emails from us by clicking on the unsubscribe link in any
            marketing email.{" "}
          </p>
          <p>
            d. Automatic Information We Collect from Other Websites: We receive
            and store certain types of information when you interact with
            third-party websites that use our technology or with whom we have a
            specific agreement.{" "}
          </p>
          <p>
            e. Information from Other Sources: We may obtain information from
            other sources. An example of this is when you authorize a
            third-party website (such as the website of another Aurum Group
            Entity) to interact directly with our website or Platform to provide
            or receive information about you. In that case, we may receive
            information to identify your account with that website.
          </p>
          <p>
            {" "}
            You can make choices about our collection and use of your Data. For
            example, you may want to access, edit or remove your Data on our
            website or Platform. When you are asked to provide Data, you may
            decline. For more information, please see the section below, titled
            “Your Rights and Choices”.
          </p>
          <p>
            {" "}
            The User is aware that a ‘Cookie’ is a small piece of information
            stored by a web server on a web browser so it can later be traced
            back from that particular browser, and that cookies are useful for
            enabling the browser to remember information specific to a given
            user, including but not limited to a User's login identification,
            password, etc.{" "}
          </p>
          <p>
            The User is aware that the Website/Platform places both permanent
            and temporary cookies in the User's computer's hard drive and web
            browser, and does hereby expressly consent to the same. The User is
            further aware that the Website uses data collection devices such as
            cookies on certain pages of the Website to help analyse web page
            flow, measure promotional effectiveness, and promote trust and
            safety, and that certain features of the Website/Platform are only
            available through the use of such cookies.
          </p>
          <p>
            {" "}
            While the User is free to decline the Website's cookies if the
            User's browser permits, the User may consequently be unable to use
            certain features on the Website. By continuing the use, you are
            agreeing to our use of cookies. If you do not agree to our use of
            cookie, you can block them in your browser setting, but you may lose
            some functionality on the Site.
          </p>
        </p>
        <h1 className="tandch1">4. DATA SHARED BY YOU</h1>
        <p>
          Platform may collect your Data in several ways from your use of our
          website or Platform. For instance:
        </p>
        <p>
          {" "}
          (a) when you register with us to receive our products and/or services;
        </p>
        <p>
          {" "}
          (b) when you conduct a transaction or attempt a transaction on our
          website or Platform;
        </p>
        <p> (c) when you complete surveys conducted by or for us; </p>
        <p>
          (d) when you elect to receive any communications (including
          promotional offers) from us;
        </p>
        <p>
          (e) from the information gathered by your visit to our website or
          Platform;
        </p>
        <h1 className="tandch1"> 5. DATA </h1>
        <p>THAT IS COLLECTED AUTOMATICALLY </p>
        <p>
          (a) We automatically collect some information when you visit our
          website or use Platform. This information helps us to make
          improvements to our content and navigation. The information collected
          automatically includes your IP address.
        </p>
        <p>
          {" "}
          (b) Our web servers or affiliates who provide analytics and
          performance enhancement services collect IP addresses, operating
          system details, browsing details, device details and language
          settings. This information is aggregated to measure the number of
          visits, average time spent on the site, pages viewed and similar
          information. We use this information to measure the site usage,
          improve content and to ensure safety and security, as well enhance
          performance of our website or Platform.
        </p>
        <p>
          {" "}
          (c) We may collect your Data automatically via Cookies, pixels and
          similar technologies in line with settings on your browser. For more
          information about Cookies, please see the section below, titled
          “Cookies, Pixels and Similar Technologies”.{" "}
        </p>
        <p>
          (d) We automatically collect Log Data which may include information
          such as your IP address, browser type, operating system, the referring
          web page, pages visited, location, your mobile carrier, device, search
          terms, and cookie information. We receive Log Data when you interact
          with our Services, for example, when you visit our Website and / or
          Mobile App, sign into our Services, or interact with our email
          notifications. We use Log Data to provide our Services and to measure,
          customize, and improve them. This policy does not apply to, nor do we
          take any responsibility for any information that is collected by any
          third party either using the Services or through any links on the
          Website and / or Mobile App or through any of the advertisements.
        </p>
      </div>
    </>
  );
}
export default PrivacyPolicy;
